config/routes.rb
Rails.application.routes.draw do
  post '/rydes/active', to: 'rydes#finish'  
  post '/rydes/:id', to: 'rydes#add'
  get '/rydes/active', to: 'rydes#active'
  resources :users 
  resources :rydes
  resources :sessions
  root 'sessions#index'
  get '/login', to: 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord
    # def compute_price
    #     if @ryde.starting_location && @ryde.ending_location
    #         price = (@ryde.starting_lcation.au - @ryde.ending_location.au).abs * 8000000
    #         "$ #{price}"
    #     end
    # end

    # def compute_time
    #     if @ryde.starting_location && @ryde.ending_location
    #         time = (@ryde.starting_lcation.au - @ryde.ending_location.au).abs * 120
    #         "#{time} days"
    #     end
end

app/models/ryde.rb
class Ryde < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :rydes, dependent: :destroy
    has_secure_password
    has_attached_file :image, styles: { medium: "500x500>", thumb: "250x250>" }, presence: true
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    
    private
    def set_defaults 
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  private
  helper_method :current_user
  helper_method :price
  helper_method :time

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def price
    number_to_currency((((Destination.find_by(name: @ryde.starting_location).au - Destination.find_by(name: @ryde.ending_location).au).abs * 10998213) + 6000000).to_d)
  end

  def time
    ((Destination.find_by(name: @ryde.starting_location).au - Destination.find_by(name: @ryde.ending_location).au).abs * 160).to_i 
  end

  def authorize
    redirect_to root_path if current_user.nil?
  end

  def authorize_pilot
    redirect_to rydes_path unless current_user.pilot? if current_user
  end

  def authorize_ryder
    redirect_to rydes_path if current_user.pilot? if current_user
  end

  def no_more_rydes
    redirect_to rydes_path unless current_user.rydes.order('created_at DESC').first.finished if current_user.rydes.length > 0
  end

end

app/controllers/rydes_controller.rb
class RydesController < ApplicationController
    before_action :authorize
    before_action :authorize_pilot, only: [:show]
    before_action :authorize_ryder, only: [:edit, :new]
    before_action :no_more_rydes, only: [:new]
    def index
        @rydes = Ryde.all.order("created_at DESC")
    end

    def new
        @ryde = Ryde.new
    end

    def create 
        @ryde = Ryde.new(ryde_params)
        @ryde.user_id = current_user.id
        if @ryde.save
            redirect_to rydes_path
        else
            render :new
        end
    end

    def show
        @ryde = Ryde.find(params[:id])
    end

    def edit
        @ryde = Ryde.find(params[:id])
    end
    
    def update
        @ryde = Ryde.find(params[:id])
        if @ryde.update_attributes(ryde_params)
            redirect_to rydes_path
        else
            render :edit
        end
    end

    def destroy
        @ryde = Ryde.find(params[:id]).destroy
        redirect_to rydes_path
    end

    def active 
    end

    def add
        @ryde = Ryde.find(params[:id])
        if @ryde.update_attributes(pilot_id: current_user.id)
            redirect_to rydes_active_path
        else
            render
        end
    end

    def finish
        @ryde = Ryde.where(pilot_id: current_user.id).order("updated_at DESC").first
        if @ryde.update_attributes(finished: true)
            redirect_to rydes_path
        else
            render
        end
    end

private
    def ryde_params
        params.require(:ryde).permit(:starting_location, :ending_location, :pilot_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :authorize_pilot, except: [:destroy] 
    before_action :authorize_ryder, except: [:destroy] 
    def index
    end
    
    def new
    end

    def create 
        user = User.find_by(email: params[:email])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            if user.pilot
                redirect_to rydes_path
            else
                unless Ryde.where(user_id: current_user.id).order("created_at DESC").first.finished
                    redirect_to rydes_path
                else
                    redirect_to new_ryde_path
                end
            end

        else
            render :new
        end
    end
    def destroy
        session[:user_id] = nil
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authorize, except: [:new, :create]
    before_action :authorize_pilot, only: [:new]
    before_action :authorize_ryder, only: [:new]
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if params[:pilot]
            @user.pilot = true
        end
        if @user.save
            session[:user_id] = @user.id
            if @user.pilot
                redirect_to rydes_path
            else 
                redirect_to new_ryde_path
            end
        else
            render :new
        end
    end

    def show
        @user = User.find_by(email: current_user.email)
    end

    def edit
    end

    def update
        if current_user.update_attributes(user_params)
            redirect_to user_path 
        else
            render :edit
        end
    end


    private 
    def user_params
        params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation, :image, :pilot )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>RydeApp</title>
    <%= csrf_meta_tags %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">


    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
<% if current_user %>
<div class="container-fluid">
  <div class="row blackrow">
    <div class="col col-left">
      RYDE
    </div>
    <div class="col col-right">
      Welcome, <%= current_user.first_name %>
    </div>
  </div>
</div>
<div class="container-fluid">
<div class="row">
  <div class="col-sm-4 black-line">
    <div class="divider">
      <div class="weird">
        <%= link_to 'Request', new_ryde_path unless current_user.pilot %>
        <%= link_to 'Active', rydes_active_path if current_user.pilot %>
      </div>
      <div class="weird">
        <%= link_to 'Rydes', rydes_path %>
      </div>
      <div class="weird">
        <%= link_to 'History', user_path(id: current_user.id) %>
      </div>
      <div class="weird">
        <%= link_to 'Logout', session_path('log_out'), method: :delete %>
      </div>
    </div>
    <div>
      <div class="profile-header">
        <br>
        <%= image_tag current_user.image.url, size: "150x150" %>
        <br>
        <span class="email"> <%= current_user.email %> </span>
        <br> 
        <%= link_to 'Edit Profile', edit_user_path(id: current_user.id) %>
      </div>
    </div>
  </div>
  <div class="col-sm-7">
    <div class="container">
      <%= yield %>
    </div>
  </div>
</div>
</div>
<br>
<% else %>
  <br><br>
  <%= yield %>
<% end %>
    <script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/rydes/active.html.erb
<% if current_user.pilot %>
    <% Ryde.all.where(pilot_id: current_user.id).each do |ryde| %>
        <% unless ryde.finished %>
            <div>
                <h1>Active Ride</h1><br>
                <%= image_tag User.find(ryde.user_id).image.url, size: '75x75' %>
                <%= User.find(ryde.user_id).first_name %>&nbsp;<%= User.find(ryde.user_id).last_name[0] %>.
                <br>
                <strong>From:</strong> <%= ryde.starting_location %>, <%= Destination.find_by(name: ryde.starting_location).location %>
                <br>
                <strong>To:</strong> <%= ryde.ending_location %>, <%= Destination.find_by(name: ryde.ending_location).location %>
                <br>
                <strong>Price:</strong> <%= number_to_currency((((Destination.find_by(name: ryde.starting_location).au - Destination.find_by(name: ryde.ending_location).au).abs * 10998213) + 6000000).to_d) %>
                <br>
                <strong>Time:</strong> <%= ((Destination.find_by(name: ryde.starting_location).au - Destination.find_by(name: ryde.ending_location).au).abs * 160).to_i %> days
                <br>
                <%= link_to "Finish", rydes_active_path, method: :finish %>
            </div>
        <% end %>
    <% end %>
<% end %>

app/views/rydes/edit.html.erb
<br>
<%= form_for @ryde do |f| %>
    From:
    <br>
    <%= f.collection_select(:starting_location, Destination.all, :name, :name, {prompt: "Starting Location"}, {include_blank: true, required: true}) %>
    <br>
    To:
    <br>
    <%= f.collection_select(:ending_location, Destination.all, :name, :name, {prompt: "Ending Location"}, {include_blank: true, required: true}) %>
    <br><br>
    <%= f.submit "Edit Ryde Request" %>
<% end %>

app/views/rydes/index.html.erb
<div class="container-fluid">
<% unless current_user.pilot %>
    <h1>My Rydes </h1>
    <br>
    <% if current_user.rydes.length > 0 %>
        <% if current_user.rydes.order('created_at DESC').first.finished %>
            <%= link_to "<button class='btn btn-lg'>REQUEST A RYDE</button>".html_safe, new_ryde_path %>
        <% end %>
    <% else %>
        It looks like you have no rydes! 
        <br>
        <%= link_to "<button class='btn btn-lg'>REQUEST A RYDE</button>".html_safe, new_ryde_path %>
    <% end %>
    <% @rydes.each do |ryde| %>
        <% if ryde.user_id == current_user.id %>
        <div>
            <% if ryde.pilot_id %>
                <br>
                <%= image_tag User.find(ryde.pilot_id).image.url, size: '75x75' %>
                <br>
                <%= User.find(ryde.pilot_id).first_name %>
                <%= User.find(ryde.pilot_id).last_name[0] %>. accepted this ryde.
                <br>
            <% end %>
            <div>
                <strong>From:</strong> <%= ryde.starting_location %>, <%= Destination.find_by(name: ryde.starting_location).location %>
                <br>
                <strong>To:</strong> <%= ryde.ending_location %>, <%= Destination.find_by(name: ryde.ending_location).location %>
                <br>
                <strong>Price:</strong> <%= number_to_currency((((Destination.find_by(name: ryde.starting_location).au - Destination.find_by(name: ryde.ending_location).au).abs * 10998213) + 6000000).to_d) %>
                <br>
                <strong>Time:</strong> <%= ((Destination.find_by(name: ryde.starting_location).au - Destination.find_by(name: ryde.ending_location).au).abs * 160).to_i %> days
                <br>
                <% unless ryde.finished %>
                    <%= link_to "Edit", edit_ryde_path(id: ryde.id) %> 
                    &nbsp;&nbsp;|&nbsp;&nbsp;
                    <%= link_to "Delete", ryde_path(id: ryde.id), method: :delete %>
                <% else %>
                    Ryde Finished: <%= ryde.updated_at.strftime("%B %d, %Y") %>
                <% end %>
            </div>
        </div>
        <% end %>
    <% end %>
<% else %> 
    <h1>Available Rydes</h1>
    <br>
    <% @rydes.each do |ryde| %>
        <% unless ryde.pilot_id %>
            <div>
                <%= image_tag User.find(ryde.user_id).image.url, size: '75x75' %>
                <%= User.find(ryde.user_id).first_name %>&nbsp;<%= User.find(ryde.user_id).last_name[0] %>.
                <br>
                <div>
                    <strong>From:</strong> <%= ryde.starting_location %>
                    <br>
                    <strong>To:</strong> <%= ryde.ending_location %>
                    <br>
                    <%= link_to "View Ryde", ryde_path(id: ryde.id) %>
                </div>
            </div>
        <% end %>
    <% end %>
<% end %>
</div>

app/views/rydes/new.html.erb
<div>
<%= form_for @ryde do |f| %>
    <h3> Where would you like to start? </h3>
    <%= f.collection_select(:starting_location, Destination.all, :name, :name, {prompt: "Select a launch site"}, {include_blank: true, required: true}) %>
    <br><br>
    <h3> Where would you like to ryde? </h3>
    <%= f.collection_select(:ending_location, Destination.all, :name, :name, {prompt: "Select a destination"}, {include_blank: true, required: true}) %>
    <br><br>
    <%= f.submit 'Request Ryde' %>
<% end %>
</div>

app/views/rydes/show.html.erb
<div>
    <h1>Ryde Details</h1>
    <br>
    <%= image_tag User.find(@ryde.user_id).image.url, size: '75x75' %>
    <%= User.find(@ryde.user_id).first_name %> <%= User.find(@ryde.user_id).last_name[0] %>.
    <br>
    <div class="ryde">
        <strong>From:</strong> <%= @ryde.starting_location %>, <%= Destination.find_by(name: @ryde.starting_location).location %>
        <br>
        <strong>To:</strong> <%= @ryde.ending_location %>, <%= Destination.find_by(name: @ryde.ending_location).location %>
        <br>
        <strong>Price:</strong> <%= number_to_currency((((Destination.find_by(name: @ryde.starting_location).au - Destination.find_by(name: @ryde.ending_location).au).abs * 10998213) + 6000000).to_d) %>
        <br>
        <strong>Time:</strong> <%= ((Destination.find_by(name: @ryde.starting_location).au - Destination.find_by(name: @ryde.ending_location).au).abs * 160).to_i %> days
        <br>
    </div>
    <% if Ryde.all.where(pilot_id: current_user.id).first.nil? %>
        <%= form_tag ryde_path do%>
            <%= submit_tag 'Accept' %> 
        <% end %> 
    <% elsif Ryde.all.where(pilot_id: current_user.id).order('updated_at DESC').first.finished %>
        <%= form_tag ryde_path do%>
            <%= submit_tag 'Accept' %> 
        <% end %> 
    <% end %>
    <%= link_to 'Back', rydes_path %>
</div>

app/views/users/edit.html.erb
<h1> Edit Profile </h1>
Email: <%= current_user.email %><br>
<%= form_for current_user do |f| %>
<%= f.text_field :first_name, placeholder: 'First Name' %>
    <br>
    <%= f.text_field :last_name, placeholder: 'Last Name' %>
    <br>
    <%= f.text_field :email, placeholder: 'Email' %>
    <br>
    <%= f.password_field :password, placeholder: 'Password' %>
    <br> 
    <%= f.password_field :password_confirmation, placeholder: 'Password' %>
    <br>
    <%= f.file_field :image %>
    <br><br>
    <%= f.submit 'Edit Profile' %>
<% end %>

app/views/users/new.html.erb
<div class="container-fluid login-page">
<h1> Create Account </h1>
<% path = params.has_key?(:pilot) ? users_path(pilot: true) : users_path %>
<%= form_for @user, url: path do |f| %>
    <%= f.text_field :first_name, placeholder: 'First Name', required: true %>
    <br>
    <%= f.text_field :last_name, placeholder: 'Last Name', required: true %>
    <br>
    <%= f.text_field :email, placeholder: 'Email', required: true %>
    <br>
    <%= f.password_field :password, placeholder: 'Password', required: true %>
    <br> 
    <%= f.password_field :password_confirmation, placeholder: 'Password', required: true %>
    <br>
    <%= f.label :image %>
    <%= f.file_field :image, required: true%>
    <br>
    <% if params[:pilot] %>
        <%= f.label :upload_license %>
        <%= f.file_field :license, required: true %>
        <br>
        <% @user.pilot = true %>    
    <% end %>
    <%= f.submit 'Create Account' %>
<% end %>
</div>

app/views/users/show.html.erb
<div class="ryde">
<% if @user.pilot %>
    <% Ryde.all.order("created_at DESC").each do |ryde| %> 
        <% if ryde.pilot_id.to_i == @user.id %>
            <% unless ryde.finished %>
            <% else %>
                <div>
                    <br>
                    <%= image_tag User.find(ryde.user_id).image.url, size: '35x35' %>
                    <%= User.find(ryde.user_id).first_name %>&nbsp;<%= User.find(ryde.user_id).last_name[0] %>.
                    <br>
                    <strong>Finished:</strong> <%= ryde.updated_at.strftime("%B %d, %Y") %>
                    <br>
                    <strong>From:</strong> <%= ryde.starting_location %>
                    <br>
                    <strong>To:</strong> <%= ryde.ending_location %>
                    <br> 
                    <strong>Price:</strong> <%= number_to_currency((((Destination.find_by(name: ryde.starting_location).au - Destination.find_by(name: ryde.ending_location).au).abs * 10998213) + 6000000).to_d) %>
                    <br>
                </div>
            <% end %>
        <% end %>
    <% end %>
<% else %>
    <% Ryde.all.order("created_at DESC").each do |ryde| %>
        <% if ryde.user_id.to_i == current_user.id %>
            <% unless ryde.finished %>
                    <div>
                        <strong>Active Ryde</strong> <br>
                        <strong>From:</strong> <%= ryde.starting_location %>, <%= Destination.find_by(name: ryde.starting_location).location %>
                        <br>
                        <strong>To:</strong> <%= ryde.ending_location %>, <%= Destination.find_by(name: ryde.ending_location).location %>
                        <br>
                        <strong>Price:</strong> <%= number_to_currency((((Destination.find_by(name: ryde.starting_location).au - Destination.find_by(name: ryde.ending_location).au).abs * 10998213) + 6000000).to_d) %>
                        <br>
                        <strong>Time:</strong> <%= ((Destination.find_by(name: ryde.starting_location).au - Destination.find_by(name: ryde.ending_location).au).abs * 160).to_i %> days
                        <br><br>
                    </div>
            <% else %>
                <div>
                    <strong>Ryde Finished:</strong> <%= ryde.updated_at.strftime("%B %d, %Y") %>
                    <br>
                    <strong>From:</strong> <%= ryde.starting_location %>, <%= Destination.find_by(name: ryde.starting_location).location %>
                    <br>
                    <strong>To:</strong> <%= ryde.ending_location %>, <%= Destination.find_by(name: ryde.ending_location).location %>
                    <br>
                    <strong>Price:</strong> <%= number_to_currency((((Destination.find_by(name: ryde.starting_location).au - Destination.find_by(name: ryde.ending_location).au).abs * 10998213) + 6000000).to_d) %>
                    <br>
                    <strong>Time:</strong> <%= ((Destination.find_by(name: ryde.starting_location).au - Destination.find_by(name: ryde.ending_location).au).abs * 160).to_i %> days
                    <br><br>
                </div>
            <% end %>
        <% end %>
    <% end %>
<% end %>
</div>